// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/get-profile.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/data/projects.ts
var projects = [
  {
    id: "1",
    title: "MOBOCHECK_PLATFORM",
    description: "Mobocheck Backoffice is a full-stack, multi-role enterprise dashboard built with React and TypeScript. Permissions for all roles\u2014including admins\u2014are managed in the backend via Casbin and sent dynamically to the frontend, ensuring each user sees only the features allowed for their role. The platform includes secure REST APIs, role-based authentication, real-time updates, database operations, notifications, activity logging, and a responsive dashboard for managing users, devices, orders, licenses, and organization settings according to assigned permissions.",
    techStack: ["React", "Node.js", "My_SQL", "Casbin", "Tailwind CSS"],
    image: "/Mobo.png",
    githubUrl: "https://github.com",
    liveUrl: "https://mobocheck.com"
  },
  {
    id: "2",
    title: "QYRA_AI_ASSISTENCE",
    description: "A comprehensive AI-driven ecosystem designed to streamline daily life. Seamlessly integrated with the Esqyra Watch, the application delivers complete information through fluid voice and chat interactions. It merges intelligent task management with proactive health and productivity insights, offering personalized recommendations, real-time location tracking, and local weather updates. The system also features a curated news aggregator\u2014covering politics, social trends, and global events\u2014all visualized within a sleek, fully responsive dashboard.",
    techStack: ["React_Native", "TS", "REST API", "My_SQL", "Tailwind CSS"],
    image: "/Qyra.png",
    githubUrl: "https://github.com",
    liveUrl: "https://app.esqyra.com"
  },
  {
    id: "3",
    title: "Events Management System",
    description: "Event Management System is a full-stack web application designed to simplify the process of planning and managing events. The platform allows organizers to create events, manage schedules, register participants, track attendees, and handle event-related operations in an efficient way. Users can browse upcoming events, register online, and receive real-time updates. Admins or organizers can manage event details, monitor registrations, and control permissions based on user roles. The system focuses on performance, usability, and scalability, making event coordination easier for both organizers and participants.",
    techStack: ["React", "Firebase", "Redux", "WebSocket", "Material UI"],
    image: "/Events.png",
    githubUrl: "https://github.com"
  },
  {
    id: "4",
    title: "FreelanceHub Marketplace",
    description: "Full-stack freelance marketplace platform connecting clients with freelancers. Features complete project lifecycle management from posting to payment, with advanced Casbin-based RBAC system for three user roles (CLIENT, FREELANCER, ADMIN). Includes project bidding workflow, proposal management, contract execution, secure JWT authentication, and role-specific dashboards. Built with MVC architecture, complex relational database with 8 models using Prisma ORM, and responsive UI for seamless user experience across all roles.",
    techStack: ["React", "TypeScript", "Node.js", "Express", "MySQL", "Prisma", "Casbin", "Tailwind CSS"],
    image: "/freelancer.png",
    githubUrl: "https://github.com"
  }
];
var skillCategories = [
  {
    title: "Frontend",
    skills: [
      { name: "React" },
      { name: "React Native" },
      { name: "TypeScript" },
      { name: "Next.js" },
      { name: "Tailwind CSS" },
      { name: "Framer Motion" },
      { name: "Redux" }
    ]
  },
  {
    title: "Backend",
    skills: [
      { name: "Node.js" },
      { name: "Express" },
      { name: "Prisma ORM" },
      { name: "JWT Authentication" },
      { name: "REST APIs" },
      { name: "Socket.io" },
      { name: "Docker" },
      { name: "AWS" }
    ]
  },
  {
    title: "Tools",
    skills: [
      { name: "Git, GitHub" },
      { name: "VS Code" },
      { name: "Figma" },
      { name: "Vercel" },
      { name: "Netlify" },
      { name: "AWS, Digital Ocean" },
      { name: "Cursor" },
      { name: "Postman" }
    ]
  }
];
var experiences = [
  {
    id: "1",
    company: "MoboCheck Web Platform (Mobocheck)",
    role: "Full Stack Developer",
    period: "2026 \u2014 Present",
    description: "Spearheading production web platform development with cutting-edge enterprise features using React.js, Node.js, and MySQL.",
    responsibilities: [
      "Engineered high-performance full-stack web applications using React.js for frontend and Node.js for backend services",
      "Architected and deployed Casbin-based authorization framework enforcing granular RBAC/ABAC policies across mission-critical platform modules",
      "Pioneered custom permission middleware layer on React frontend, enabling real-time access control and dynamic component rendering",
      "Designed scalable UI architecture with Redux Toolkit, achieving predictable state management and measurable performance gains",
      "Crafted robust RESTful APIs with Node.js and optimized MySQL schemas for high-traffic production workloads",
      "Drove cross-functional collaboration with backend teams, ensuring seamless API integration and enterprise-grade data security"
    ]
  },
  {
    id: "2",
    company: "QYRA AI Assistance (Mobocheck)",
    role: "React Native Developer",
    period: "2025 \u2014 2026",
    description: "Led end-to-end mobile development for innovative AI-powered cross-platform application.",
    responsibilities: [
      "Orchestrated React Native development for iOS and Android, overseeing architecture design through production deployment",
      "Maximized runtime performance by strategically implementing React.memo, useMemo, and useCallback, eliminating unnecessary re-renders",
      "Implemented sophisticated API-driven state management using advanced React hooks for seamless real-time data synchronization",
      "Integrated AI-powered capabilities through RESTful APIs with comprehensive error handling and intelligent loading states",
      "Partnered with backend engineering teams to align API contracts and deliver fluid real-time user experiences"
    ]
  },
  {
    id: "3",
    company: "Event Management System (University Project)",
    role: "Full Stack Developer",
    period: "2024 \u2014 2025",
    description: "Independently developed comprehensive full-stack platform for streamlined event operations.",
    responsibilities: [
      "Built feature-rich event management system with intuitive event creation and participant registration workflows",
      "Developed scalable REST API architecture and normalized MySQL database schema from ground up",
      "Delivered responsive, type-safe frontend using React.js with TypeScript for enhanced code reliability",
      "Owned complete SDLC from requirements gathering through successful production deployment"
    ]
  },
  {
    id: "4",
    company: "FreelanceHub Marketplace (Personal Project)",
    role: "Full Stack Developer",
    period: "2025",
    description: "Built full-stack freelance marketplace platform as a personal learning project to master advanced authentication, authorization, and complex database relationships.",
    responsibilities: [
      "Developed complete marketplace platform using React TypeScript, Node.js/Express, and MySQL with Prisma ORM",
      "Implemented advanced RBAC authorization system using Casbin with dynamic role and permission management",
      "Architected complex database schema with 8 models handling users, projects, proposals, payments, and permissions",
      "Built secure JWT authentication with bcrypt password hashing and multi-level route protection",
      "Created three distinct user workflows: client project posting, freelancer bidding system, and admin platform management",
      "Designed MVC architecture with organized controllers, models, and service layers for scalable code structure"
    ]
  }
];
var personalInfo = {
  name: "Muhammad Zohaib",
  role: "Full Stack Developer",
  bio: "Software developer with 1+ year of hands-on experience building modern web and mobile applications. Focused on writing clean, maintainable code and creating intuitive user interfaces. Experienced in the React ecosystem including React, Next.js, React Native, along with backend development using Node.js. Passionate about delivering scalable and user-friendly solutions..",
  email: "mzohaibbhatti604@gmail.com",
  github: "https://github.com/M-zohaib-developer",
  linkedin: "https://www.linkedin.com/in/muhammad-zohaib-1a6972234/",
  location: "Lahore, Pakistan"
};

// src/lib/mcp/tools/get-profile.ts
var get_profile_default = defineTool({
  name: "get_profile",
  title: "Get profile",
  description: "Returns the developer's public profile: name, role, bio, location, and public contact links (email, GitHub, LinkedIn).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(personalInfo, null, 2) }],
    structuredContent: personalInfo
  })
});

// src/lib/mcp/tools/list-projects.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^4.4.3";
var list_projects_default = defineTool2({
  name: "list_projects",
  title: "List projects",
  description: "Returns the portfolio's projects with title, description, tech stack, and links. Optionally filter by a technology (case-insensitive substring match on the tech stack).",
  inputSchema: {
    tech: z.string().optional().describe("Optional technology filter, e.g. 'React' or 'PostgreSQL'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ tech }) => {
    const filtered = tech ? projects.filter(
      (p) => p.techStack.some((t) => t.toLowerCase().includes(tech.toLowerCase()))
    ) : projects;
    return {
      content: [{ type: "text", text: JSON.stringify(filtered, null, 2) }],
      structuredContent: { projects: filtered, count: filtered.length }
    };
  }
});

// src/lib/mcp/tools/list-skills.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^4.4.3";
var list_skills_default = defineTool3({
  name: "list_skills",
  title: "List skills",
  description: "Returns the developer's skills grouped by category (Frontend, Backend, Tools).",
  inputSchema: {
    category: z2.string().optional().describe("Optional category filter (case-insensitive), e.g. 'Frontend'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ category }) => {
    const filtered = category ? skillCategories.filter(
      (c) => c.title.toLowerCase() === category.toLowerCase()
    ) : skillCategories;
    return {
      content: [{ type: "text", text: JSON.stringify(filtered, null, 2) }],
      structuredContent: { categories: filtered }
    };
  }
});

// src/lib/mcp/tools/list-experience.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
var list_experience_default = defineTool4({
  name: "list_experience",
  title: "List experience",
  description: "Returns the developer's professional experience: company, role, period, description, and responsibilities.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(experiences, null, 2) }],
    structuredContent: { experience: experiences }
  })
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "portfolio-mcp",
  title: "Muhammad Zohaib \u2014 Portfolio",
  version: "0.1.0",
  instructions: "Public tools for browsing Muhammad Zohaib's developer portfolio. Use `get_profile` for bio and contact links, `list_projects` for project details (optionally filtered by tech), `list_skills` for skills by category, and `list_experience` for work history.",
  tools: [get_profile_default, list_projects_default, list_skills_default, list_experience_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
